MODEL:
  META_ARCHITECTURE: "LapMask"
  MASK_ON: True
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
  #TEST: ("coco_2017_test-dev",)
SOLVER:
  #IMS_PER_BATCH: 16
  #BASE_LR: 0.01
  #WARMUP_FACTOR: 0.01
  #WARMUP_ITERS: 1000
  #STEPS: (60000, 80000)
  #MAX_ITER: 90000
  IMS_PER_BATCH: 8
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  WARMUP_ITERS: 500
  WARMUP_FACTOR: 0.001
  #WARMUP_ITERS: 2000
  #WARMUP_FACTOR: 0.00025
  #WARMUP_ITERS: 4000
  #WARMUP_FACTOR: 0.00025
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_VALUE: 35.0
    NORM_TYPE: 2.0
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MASK_FORMAT: "bitmask"
VERSION: 2


