MODEL:
  META_ARCHITECTURE: "LapMask"
  MASK_ON: True
  BACKBONE:
    NAME: "build_vovnet_fpn_backbone"
    FREEZE_AT: 0
  VOVNET:
    OUT_FEATURES: ["stage2", "stage3", "stage4", "stage5"]
  FPN:
    IN_FEATURES: ["stage2", "stage3", "stage4", "stage5"]
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
  #TEST: ("coco_2017_test-dev",)
SOLVER:
  IMS_PER_BATCH: 12
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  #LR_SCHEDULER_NAME: "WarmupCosineLR"
  WARMUP_ITERS: 500
  WARMUP_FACTOR: 0.001
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_VALUE: 35.0
    NORM_TYPE: 2.0
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MASK_FORMAT: "bitmask"
VERSION: 2


