_BASE_: "Base-LapMask-ResNet.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  RESNETS:
    DEPTH: 101
    DEFORM_ON_PER_STAGE: [False, True, True, True] # on Res4, Res5
    DEFORM_MODULATED: True
  LAPMASK:
    INSTANCE_CHANNELS: 768
    NUM_GRIDS: [56, 48, 36, 24, 16, 12]
    NUM_KERNELS: 96
    NUM_MASKS: 96
SOLVER:
  #STEPS: (210000, 250000)
  #MAX_ITER: 270000
  STEPS: (420000, 500000)
  MAX_ITER: 540000
INPUT:
  MIN_SIZE_TRAIN: (576, 608, 640, 672, 704, 736, 768, 800)
