_BASE_: "Base-LapMask-ResNet.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
SOLVER:
  #STEPS: (210000, 250000)
  #MAX_ITER: 270000
  STEPS: (420000, 500000)
  MAX_ITER: 540000
