_BASE_: "Base-LapMask-ResNet.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
  LAPMASK:
    INSTANCE_CHANNELS: 384
    NUM_KERNELS: 32
    NUM_MASKS: 32
    NUM_INSTANCE_CONVS: 3
    #USE_DCN_IN_INSTANCE: True
INPUT:
  MIN_SIZE_TRAIN: (256, 288, 320, 352, 384, 416, 448, 480, 512, 544, 576, 608)
  MAX_SIZE_TRAIN: 900
  MAX_SIZE_TEST: 852
  MIN_SIZE_TEST: 512
  #MAX_SIZE_TEST: 512
  #MIN_SIZE_TEST: 352

SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  STEPS: (300000, 340000)
  MAX_ITER: 360000
